# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.8

jobs:          
  test-3.8: &test-template-python3
    docker:
      - image: circleci/python:3.8.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r dev-requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 setup.py install
            tox -e py38
