name: Test

on:
  push:
    - master
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Requirements
        run: pip3 install -r requirements.txt
      - name: second
        run: pip3 install -r dev-requirements.txt
      - name: install
        run: python3 setup.py install
      - name: Testing command
        run: tox -e py38
        
        
  test-aarch64:
    strategy:
      matrix:
        pyver: [cp38-cp38]
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      py: /opt/python/${{ matrix.pyver }}/bin/python
      img: quay.io/pypa/manylinux2014_aarch64
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: aarch64
      run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
            ${{ env.img }} \
            bash -exc '${{ env.py }} -m venv .env && \
            source .env/bin/activate && \
            pip3 install -r requirements.txt && \
            pip3 install -r dev-requirements.txt && \
            python3 setup.py install && \
            tox -e py38 && \ 
            deactivate'
