name: Test

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Requirements
        run: pip3 install -r requirements.txt
      - name: second
        run: pip3 install -r dev-requirements.txt
      - name: install
        run: python3 setup.py install
      - name: Testing
        run: tox -e py38
